export const elements = {
  activeProjectLabel: document.querySelector("#active-project-label"),
  projectList: document.querySelector("#project-list"),
  projectForm: document.querySelector("#project-form"),
  projectName: document.querySelector("#project-name"),
  projectPath: document.querySelector("#project-path"),
  browseButton: document.querySelector("#browse-button"),
  refreshButton: document.querySelector("#refresh-button"),
  workspaceTitle: document.querySelector("#workspace-title"),
  phaseBadge: document.querySelector("#phase-badge"),
  goalInput: document.querySelector("#goal-input"),
  orgSelect: document.querySelector("#org-select"),
  roundsInput: document.querySelector("#rounds-input"),
  providerList: document.querySelector("#provider-list"),
  applyToggle: document.querySelector("#apply-toggle"),
  unsafeToggle: document.querySelector("#unsafe-toggle"),
  startButton: document.querySelector("#start-button"),
  validationMessage: document.querySelector("#validation-message"),
  monitorTitle: document.querySelector("#monitor-title"),
  runTimes: document.querySelector("#run-times"),
  transcriptView: document.querySelector("#transcript-view"),
  providerState: document.querySelector("#provider-state"),
  handoffView: document.querySelector("#handoff-view"),
  blockerList: document.querySelector("#blocker-list"),
  fileList: document.querySelector("#file-list")
};
